base_url = "https://translatingmlresearch.github.io/RCMLR/"
compile_sass = true
build_search_index = false
generate_feeds = false
minify_html = true
theme = "academic-workshop"
ignored_static = ["sponsorship_prospectus.pdf","travel-support-CVs/*"]

[markdown]
highlight_code = false
smart_punctuation = true

[extra]
title = {tagline = "NeurIPS 2026 Workshop", title = "Responsible Communication of Machine Learning Research in Biomedicine", subtitles = ["Sydney, Australia", "December 2026"]}
banner = {extension = "svg", size = "fit-height", fade = true}
buttons = [{name = "Home", url = "/RCMLR/"}, {name = "Call for papers", url = "/RCMLR/call-for-papers/"}, {name = "Speakers and Agenda", url = "/RCMLR/speakers-and-agenda/"}]
header_pages = [{name = "Home", url = "/RCMLR/"},{name = "Call for papers", url = "/RCMLR/call-for-papers/"},{name = "Speakers and Agenda", url = "/RCMLR/speakers-and-agenda/"}]
