base_url = "https://translatingmlresearch.github.io/RCMLR/"
title = "RCMLR: Responsible Communication of ML Research in Biomedicine"
description = "A NeurIPS 2026 workshop bridging the gap between ML researchers and the clinicians, policymakers and domain scientists who must act on their findings."
compile_sass = true
build_search_index = false
generate_feeds = false
minify_html = true
theme = "academic-workshop"
ignored_static = ["sponsorship_prospectus.pdf","travel-support-CVs/*"]

[markdown]
highlight_code = false
smart_punctuation = true

[extra]
title = {tagline = "NeurIPS Workshop", title = "Responsible Communication of Machine Learning Research in Biomedicine", subtitles = ["Sydney, Australia", "December 2026"]}
banner = {extension = "jpg", size = "fit-height", fade = true}
buttons = [{name = "Home", url = "/RCMLR/"}, {name = "Call for papers", url = "/RCMLR/call-for-papers/"}]
header_pages = []
